### ISSUE TITLE
Unable to customize payment methods

### ISSUE THREAD

**Issue by Mixerboy24** [paytrail/paytrail-for-woocommerce#131]
**Is your feature request related to a problem? Please describe.**

Currently, there's a limitation with Paytrail integration in WooCommerce where merchants cannot select specific payment methods to offer to their customers. This results in a situation where all payment methods defined in the Merchant Dashboard are enforced enabled, leading to a lack of flexibility. For instance, if a merchant manages multiple WooCommerce online stores, they are compelled to provide payment methods that might not be relevant or usable for certain customer groups.

**Describe the solution you'd like**

To address this issue, i propose adding an option within the plugin's settings that allows merchants to customize the available payment methods. This can be achieved by incorporating checkboxes next to each payment method, enabling merchants to selectively enable or disable them based on their preferences and customer needs.

Potential Benefits:
- Enhanced flexibility: Merchants can tailor the payment methods offered to align with their business model and customer preferences.
- Improved customer experience: By providing only relevant payment methods, the checkout process becomes smoother and more intuitive for customers.
- Better alignment with business goals: Merchants can optimize their payment offerings to encourage desired payment behaviors and streamline operations.

**Describe alternatives you've considered**

- Grouping payment methods: Alternatives such as grouping payment methods into categories like Banks, Cards, Mobile Payments, and Financing can provide additional organization and clarity.
- Individual customization: Alternatively, allowing merchants to customize payment methods individually, providing granular control over the available options.

**Additional context**

By implementing this feature, merchants using Paytrail integration in WooCommerce can efficiently manage their payment methods, enhancing both operational efficiency and customer satisfaction.

This is implemented, for example, in the [Paytrail for WHMCS module created by Net9 Oy](https://marketplace.whmcs.com/product/4801-paytrail-for-whmcs).

![image](https://github.com/paytrail/paytrail-for-woocommerce/assets/37768995/eab48502-db4a-402f-910c-7e6179d87ac1)

**Comment by loueranta-paytrail** [comment]
We don't support this approach as it will become hard to keep track of the payment methods when they can enabled/disabled in multiple places. We also regularly roll-out new payment methods, so keeping the list updated is also cumbersome. 

If you have multiple stores, we suggest you use multiple Merchant IDs, one for each store, so you can then manage the payment methods per store in the Paytrail Admin Panel.

If you are interested on this approach, do not hesitate to contact our Customer Service at asiakaspalvelu@paytrail.com
