### ISSUE TITLE
Change esc_html() to wp_kses_post() function

### ISSUE THREAD

**Issue by jambojet-dima** [paytrail/paytrail-for-woocommerce#134]
https://github.com/paytrail/paytrail-for-woocommerce/blame/0c23b1b39af4dc7960bf75897cf0b1b70dffe8b1/src/View/PaymentDescription.php#L14

**Comment by chrisgan** [comment]
@jambojet-dima Is there specific HTML you are expecting to be able to use in the Payment Provider description?
I ask because I think it would be preferable if we use 'wp_kses' and specify the Allowed HTML. I'm guessing it would only be basic formatting, or would links be expected for instance?

**Comment by jambojet-dima** [comment]
For example, the HTML <img> tag.
