### ISSUE TITLE
Undefined variable $test_mode_enabled

### ISSUE THREAD

**Issue by mhgx** [paytrail/paytrail-for-woocommerce#146]
Undefined variable $test_mode_enabled in [paytrail-for-woocommerce/src/Gateway.php on line 220](https://github.com/paytrail/paytrail-for-woocommerce/blame/e841bb652bbcdff0125105e0a53cfbe40d348ebe/src/Gateway.php#L220)

**Comment by loueranta-paytrail** [comment]
This was fixed in 2.0.2
