### ISSUE TITLE
Order status doesn't change from "Processing" to "Refunded" after order has been refunded

### ISSUE THREAD

**Issue by sl-nikohamalainen** [paytrail/paytrail-for-woocommerce#157]
Order status doesn't change from "Processing" to "Refunded" after order has been refunded.

https://github.com/paytrail/paytrail-for-woocommerce/blob/master/src/Gateway.php#L956-L1022

This causes issues with Sensei LMS plugin because users can still access courses after order is refunded.

Our goal is to have a fully automatic refund system without admin having to manually update order statuses.

**Comment by chrisgan** [comment]
@sl-nikohamalainen 

Please can you provide more information on this?

I have tested this myself and the order changes to show a status of 'Refunded' in the Woo Commerce admin view. In the database the status is 'wc-refunded'

The code for the payment method itself does not set this status, we instead call the hook 'woocommerce_order_refunded' and Woo Commerce in turn sets the status of the order accordingly. 

Please provide as much detail as possible, including but not limited to:

- Version of the payment module you are using
- Version of Woo Commerce you are using
- Payment type used. 
  - Is it a saved card?
- Steps taken to refund the order -i.e. do you action this in the admin panel and select 'Refund via Paytrail for Woo Commerce' 
- Screen shot of the order showing the status and details of the order once refunded (please do not include any personal information)
- Are you using HPOS or legacy tables?
  - If HPOS - What is the value of 'status' for the order in the database table wp_wc_orders
  - If legacy what is the value of 'post_status' in the wp_posts table

Thanks

**Comment by sl-nikohamalainen** [comment]
The refund process seems to work with WooCommerce built-in product types, I will close this issue and continue to investigate custom product types.
