### ISSUE TITLE
Issues with updating payment method WooCommerce Subscriptions

### ISSUE THREAD

**Issue by marconmartins** [paytrail/paytrail-for-woocommerce#173]
**Describe the bug**

With WooCommerce Subscriptions it is not possible to update the credit card.

**Steps to Reproduce**

1. In the My Account page Subscriptions page, open an active subscription.
2. Click on the button to change the payment method.
3. Click on an existing card.
4. Click on the delete card.

**Expected behaviour**

The current payment method should be highlighted when loading the page. When clicked, the delete button, the selected card should be deleted.

**Actual behaviour**

There is no highlight in the currently used card. When clicked, the delete button does nothing.

There is a request to `/paytrail/card/delete` returning code 500 and the error log throws:

```
PHP Fatal error:  Uncaught Error: Class "Paytrail\WooCommercePaymentGateway\Exception" not found in /var/www/html/wordpress/wp-content/plugins/paytrail-for-woocommerce/src/Controllers/Card.php:77
Stack trace:
#0 /var/www/html/wordpress/wp-content/plugins/paytrail-for-woocommerce/src/Controllers/Card.php(34): Paytrail\WooCommercePaymentGateway\Controllers\Card->validate_request()
#1 /var/www/html/wordpress/wp-content/plugins/paytrail-for-woocommerce/src/Controllers/AbstractController.php(12): Paytrail\WooCommercePaymentGateway\Controllers\Card->delete()
#2 /var/www/html/wordpress/wp-content/plugins/paytrail-for-woocommerce/src/Router.php(89): Paytrail\WooCommercePaymentGateway\Controllers\AbstractController->execute('delete')
#3 /var/www/html/wordpress/wp-includes/class-wp-hook.php(324): Paytrail\WooCommercePaymentGateway\Router->routes('/var/www/html/w...')
#4 /var/www/html/wordpress/wp-includes/plugin.php(205): WP_Hook->apply_filters('/var/www/html/w...', Array)
#5 /var/www/html/wordpress/wp-includes/template-loader.php(104): apply_filters('template_includ...', '/var/www/html/w...')
#6 /var/www/html/wordpress/wp-blog-header.php(19): require_once('/var/www/html/w...')
#7 /var/www/html/wordpress/index.php(17): require('/var/www/html/w...')
#8 {main}
  thrown in /var/www/html/wordpress/wp-content/plugins/paytrail-for-woocommerce/src/Controllers/Card.php on line 77
```

Commenting out `Paytrail\WooCommercePaymentGateway\Controllers\Card->validate_request()` removes the issue and the request response is fine, but the UI is not updated. After refreshing the page the card is not displayed anymore.

**Additional context**

Paytrail for WooCommerce: 2.1.1
WooCommerce Subscriptions: 6.3.1

**Comment by kotivuori** [comment]
Thanks for reporting this @marconmartins. We’ll look into it shortly.
