### ISSUE TITLE
Critical bug in refund callback processing

### ISSUE THREAD

**Issue by thannus** [paytrail/paytrail-for-woocommerce#188]
There is a typo in the custom query variable handling for "checkout_refund_unique_id". The meta query is missing the "value" key, which results in the value not being considered when retrieving refunds by their unique id. This can result in the wrong refund being processed when the callback is received from Paytrail. We have already encountered several instances of the wrong refund being deleted when a refund cancellation was processed.

https://github.com/paytrail/paytrail-for-woocommerce/blob/7a6cba1dc96197512102b2f6c41da29a5422aeb2/src/Gateway.php#L2226

The current implementation leads to the following SQL query when fetching refunds by their unique id:
SELECT wp_posts.ID
FROM wp_posts
INNER JOIN wp_postmeta
ON ( wp_posts.ID = wp_postmeta.post_id )
WHERE 1=1
AND ( wp_postmeta.meta_key = '_checkout_refund_unique_id' )
AND wp_posts.post_type = 'shop_order_refund'
AND ((wp_posts.post_status = 'wc-pending'
OR wp_posts.post_status = 'wc-processing'
OR wp_posts.post_status = 'wc-on-hold'
OR wp_posts.post_status = 'wc-completed'
OR wp_posts.post_status = 'wc-cancelled'
OR wp_posts.post_status = 'wc-refunded'
OR wp_posts.post_status = 'wc-failed'))
GROUP BY wp_posts.ID
ORDER BY wp_posts.post_date DESC
LIMIT 0, 10

**Comment by kotivuori** [comment]
Thanks for reporting @thannus, we will update this asap.
