### ISSUE TITLE
Support for WooCommerce Blocks

### ISSUE THREAD

**Issue by loueranta-paytrail** [paytrail/paytrail-for-woocommerce#57]
Let's add support for [WooCommerce Blocks](https://woocommerce.com/products/woocommerce-gutenberg-products-block/)

**Comment by kopoi** [comment]
Hi, is there any ETA for this? Currently facing issues as this plugin is incompatible with the block-based checkout.

**Comment by arvoisa** [comment]
New block checkout is going to be default from Woo 8.3 ->

https://developer.woo.com/2023/08/18/cart-and-checkout-blocks-becoming-the-default-experience/

**Comment by loueranta-paytrail** [comment]
We should do this at the same time as #118

**Comment by jaseppan** [comment]
Are you going to add support for Checkout Block and when?

**Comment by loueranta-paytrail** [comment]
Yes, we are just picking it up from our backlog

**Comment by arvoisa** [comment]
> We should do this at the same time as #118

> Yes, we are just picking it up from our backlog

It was supposed to be added with HPOS? When can we expect this?

**Comment by Mixerboy24** [comment]
Is this still in testing? Because now I can't publish my new online store because of incompatibility.

![image](https://github.com/user-attachments/assets/9aae2254-c8e4-4cbf-9897-6c63a5c1206b)

**Comment by kotivuori** [comment]
Unfortunately this release has been delayed but we will try to get it out shortly. In the meantime we suggest using the classic shortcode checkout if possible.

**Comment by kotivuori** [comment]
Blocks support has now been added with version 2.2.0
