### ISSUE TITLE
Double orders, add calback delay to settings or some default value

### ISSUE THREAD

**Issue by karmivartio** [paytrail/paytrail-for-woocommerce#76]
**Double orders when user and callback calls return URL in web cluster**

We had problems when customer returned from Paytrail and in same time callback called callback link, thus marked order as paid two times, and in this case processed order two times and send two confirmation emails to customer. (race condition).

This can se quite hard to reproduce, because return and call back URL have to called same time in different servers.

**Solution**

Add delay to call back.

API has support for this (setCallbackDelay):
https://github.com/paytrail/paytrail-php-sdk/blob/0f1e60b81eba4b9e14d3349d8c0da2e575ddaa5b/src/Interfaces/PaymentRequestInterface.php#L213

https://docs.paytrail.com/#/?id=request-body

It would be nice to have some delay in call back (1-5 second?), or settings for this delay.

**Comment by loueranta-paytrail** [comment]
@karmivartio Thanks for the idea, we will implement this in a future release

**Comment by loueranta-paytrail** [comment]
@karmivartio We just released a new version (1.3.2) where we have added three second callback delay. I hope this helps.

**Comment by karmivartio** [comment]
Thank you!
