### ISSUE TITLE
Issue with WPML and callbacks

### ISSUE THREAD

**Issue by loueranta-paytrail** [paytrail/paytrail-for-woocommerce#83]
Original issue on wp.org: https://wordpress.org/support/topic/wpml-callbacks/

> _We noticed that some payment notifications were not being handled correctly by the Paytrail for Woocommerce plugin. We are using WPML and found that the payment notifications were being sent to our server using this URL:
> /?lang=en/paytrail/callback/index&checkout-account=xxxx…
> The added lang parameter in the beginning prevented the callback from being handled correctly by the plugin._
> 
> _The plugin seems to use home_url() when constructing the callback urls and WPML also hooks into the ‘home_url‘ filter, adding the language parameter if the current language differs from the site’s default language._
> 
> _We can fix this temporarily by adding our own custom filter to ‘home_url’ in order to override WPML’s modifications, but this should probably be handled internally by the Paytrail for Woocommerce plugin._

**Comment by thannus** [comment]
This issue is still active as of version 2.1.1. You can verify it by creating a site with WPML, adding two languages enabled, using the lang-parameter in WPML settings, viewing the site in another language and then proceeding to payment.
The callback URL sent to the Paytrail API is:

 ..."callbackUrls":{"success":"https://example.org/?lang=enpaytrail/callback/index","cancel":"https://example.org/?lang=enpaytrail/callback/index"},...

My suggestion for a fix in Router.php:
`		/**
	 * Get route action url
	 *
	 * @param $route
	 * @param $action
	 * @return string
	 */
	public static function get_url( $route, $action) {
		$home_url = esc_url(home_url('/'));
		$base_url = Plugin::BASE_URL;
		$route_base_url = self::ROUTE_BASE_URL;
		$action_base_url = self::ACTION_BASE_URL;

		if (!get_option('permalink_structure')) {
			return "{$home_url}index.php?{$route_base_url}={$route}&{$action_base_url}={$action}";
		}

		$parsed_home_url = wp_parse_url( $home_url );
		
		$site_base_url = untrailingslashit( $parsed_home_url['host'] . $parsed_home_url['path'] );
		$route_url = "{$parsed_home_url['scheme']}://{$site_base_url}/{$route}/{$action}";
		if ( isset( $parsed_home_url['query'] ) ) {
			$query = array();
			wp_parse_str( $parsed_home_url['query'], $query);
			if ( !empty( $query ) ) {
				$route_url = add_query_arg( $query, $route_url );
			}
		}
		
		return $route_url;
	}`
