### ISSUE TITLE
Images for tokenized cards not displayed at checkout

### ISSUE THREAD

**Issue by mikkosiikaniemi** [paytrail/paytrail-for-woocommerce#98]
Placeholder images for saved/tokenized payment cards are not displayed at checkout.

According to the plugin code[^1][^2], the images are being referred to using static.paytrail.com, e.g. https://static.paytrail.com/static/img/payment-methods/visa.svg. This server does not seem to exist/respond.

![image](https://github.com/paytrail/paytrail-for-woocommerce/assets/36844814/350e4794-ecce-4ab4-8496-d597b32f62f4)

[^1]: https://github.com/paytrail/paytrail-for-woocommerce/blob/master/plugin.php#L48
[^2]: https://github.com/paytrail/paytrail-for-woocommerce/blob/master/src/Gateway.php#L537

**Comment by loueranta-paytrail** [comment]
This was fixed some time ago.
